services:
  # Backend Spring Boot WebApp Service (with Frontend Built-in)
  - type: web
    name: sk-bazaar-backend
    env: docker
    plan: free
    region: ohio
    dockerFilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8080"
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://bkdidir94vhidbpch7ox-mysql.services.clever-cloud.com:3306/bkdidir94vhidbpch7ox?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: ujcoipqkp3ovweit
      - key: SPRING_DATASOURCE_PASSWORD
        value: ZpWdaK1qLTASMzMCuuIG
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

# External MySQL from Clever Cloud is being used.

