spring.application.name=SK Bazaar
server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring AI Configuration
spring.ai.google.genai.api-key=${SPRING_AI_GOOGLE_GENAI_API_KEY}
